import type { ConversationType, Facility, Owner } from "@/lib/types"


// Mock data for owners
export const owners: Owner[] = [
  {
    id: 1,
    ownerName: "John Smith",
    ownerImage: "/placeholder.svg?height=200&width=200",
    ownerEmail: "john.smith@example.com",
    ownerId: "OWN001",
    ownerAddress: "123 Main St, New York, NY 10001, United States of America",
    numberOfFacilities: 3,
    totalRevenue: 325000000,
    status: "Activated",
    province: "p1",
    district: "d1",
    phoneNumber: "+1 (555) 123-4567",
    gender: "Male",
  },
  {
    id: 2,
    ownerName: "Sarah Johnson",
    ownerImage: "/placeholder.svg?height=200&width=200",
    ownerEmail: "sarah.j@example.com",
    ownerId: "OWN002",
    ownerAddress: "456 West Ave, Los Angeles, CA 90001",
    numberOfFacilities: 1,
    totalRevenue: 87500000,
    status: "Activated",
    province: "p2",
    district: "d6",
    phoneNumber: "+1 (555) 234-5678",
    gender: "Female",
  },
  {
    id: 3,
    ownerName: "Robert Williams",
    ownerImage: "/placeholder.svg?height=200&width=200",
    ownerEmail: "r.williams@example.com",
    ownerId: "OWN003",
    ownerAddress: "789 East Blvd, Chicago, IL 60007",
    numberOfFacilities: 2,
    totalRevenue: 210000000,
    status: "Deactivated",
    province: "p5",
    district: "d18",
    phoneNumber: "+1 (555) 345-6789",
    gender: "Male",
  },
  {
    id: 4,
    ownerName: "Emily Davis",
    ownerImage: "/placeholder.svg?height=200&width=200",
    ownerEmail: "emily.d@example.com",
    ownerId: "OWN004",
    ownerAddress: "321 North Rd, Boston, MA 02108",
    numberOfFacilities: 1,
    totalRevenue: 65000000,
    status: "Activated",
    province: "p1",
    district: "d2",
    phoneNumber: "+1 (555) 456-7890",
    gender: "Female",
  },
  {
    id: 5,
    ownerName: "Michael Brown",
    ownerImage: "/placeholder.svg?height=200&width=200",
    ownerEmail: "m.brown@example.com",
    ownerId: "OWN005",
    ownerAddress: "654 South St, Miami, FL 33101",
    numberOfFacilities: 2,
    totalRevenue: 175000000,
    status: "Activated",
    province: "p4",
    district: "d14",
    phoneNumber: "+1 (555) 567-8901",
    gender: "Male",
  },
  {
    id: 6,
    ownerName: "Jennifer Wilson",
    ownerImage: "/placeholder.svg?height=200&width=200",
    ownerEmail: "j.wilson@example.com",
    ownerId: "OWN006",
    ownerAddress: "987 Downtown Ave, Seattle, WA 98101",
    numberOfFacilities: 1,
    totalRevenue: 92000000,
    status: "Deactivated",
    province: "p2",
    district: "d7",
    phoneNumber: "+1 (555) 678-9012",
    gender: "Female",
  },
  {
    id: 7,
    ownerName: "David Miller",
    ownerImage: "/placeholder.svg?height=200&width=200",
    ownerEmail: "david.m@example.com",
    ownerId: "OWN007",
    ownerAddress: "159 Riverside Dr, Austin, TX 78701",
    numberOfFacilities: 1,
    totalRevenue: 145000000,
    status: "Activated",
    province: "p3",
    district: "d11",
    phoneNumber: "+1 (555) 789-0123",
    gender: "Male",
  },
  {
    id: 8,
    ownerName: "Lisa Taylor",
    ownerImage: "/placeholder.svg?height=200&width=200",
    ownerEmail: "lisa.t@example.com",
    ownerId: "OWN008",
    ownerAddress: "753 Mountain Rd, Denver, CO 80202",
    numberOfFacilities: 1,
    totalRevenue: 195000000,
    status: "Activated",
    province: "p3",
    district: "d12",
    phoneNumber: "+1 (555) 890-1234",
    gender: "Female",
  },
  {
    id: 9,
    ownerName: "Thomas Anderson",
    ownerImage: "/placeholder.svg?height=200&width=200",
    ownerEmail: "t.anderson@example.com",
    ownerId: "OWN009",
    ownerAddress: "426 Ocean Dr, San Diego, CA 92101",
    numberOfFacilities: 1,
    totalRevenue: 78000000,
    status: "Deactivated",
    province: "p2",
    district: "d8",
    phoneNumber: "+1 (555) 901-2345",
    gender: "Male",
  },
  {
    id: 10,
    ownerName: "Amanda Martinez",
    ownerImage: "/placeholder.svg?height=200&width=200",
    ownerEmail: "a.martinez@example.com",
    ownerId: "OWN010",
    ownerAddress: "871 Valley Blvd, Phoenix, AZ 85001",
    numberOfFacilities: 1,
    totalRevenue: 155000000,
    status: "Activated",
    province: "p3",
    district: "d10",
    phoneNumber: "+1 (555) 012-3456",
    gender: "Female",
  },
]

// Mock data for facilities
export const facilities: Facility[] = [
  {
    id: 1,
    facilityName: "Central Hospital",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "123 Main St, New York, NY 10001, United States of America - Medical District Area",
    facilityId: "FAC001",
    ownerName: "John Smith",
    ownerEmail: "john.smith@example.com",
    ownerId: "OWN001",
    registerDate: "2023-01-15",
    status: "Active",
    province: "p1",
    district: "d1",
    revenue: 150000000,
  },
  {
    id: 2,
    facilityName: "Westside Clinic",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "456 West Ave, Los Angeles, CA 90001",
    facilityId: "FAC002",
    ownerName: "Sarah Johnson",
    ownerEmail: "sarah.j@example.com",
    ownerId: "OWN002",
    registerDate: "2023-02-20",
    status: "Pending",
    province: "p2",
    district: "d6",
    revenue: 87500000,
  },
  {
    id: 3,
    facilityName: "Eastside Medical Center",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "789 East Blvd, Chicago, IL 60007",
    facilityId: "FAC003",
    ownerName: "Robert Williams",
    ownerEmail: "r.williams@example.com",
    ownerId: "OWN003",
    registerDate: "2022-11-05",
    status: "Active",
    province: "p5",
    district: "d18",
    revenue: 120000000,
  },
  {
    id: 4,
    facilityName: "North Health Services",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "321 North Rd, Boston, MA 02108",
    facilityId: "FAC004",
    ownerName: "Emily Davis",
    ownerEmail: "emily.d@example.com",
    ownerId: "OWN004",
    registerDate: "2023-03-10",
    status: "Inactive",
    province: "p1",
    district: "d2",
    revenue: 65000000,
  },
  {
    id: 5,
    facilityName: "South Community Hospital",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "654 South St, Miami, FL 33101",
    facilityId: "FAC005",
    ownerName: "Michael Brown",
    ownerEmail: "m.brown@example.com",
    ownerId: "OWN005",
    registerDate: "2022-09-18",
    status: "Active",
    province: "p4",
    district: "d14",
    revenue: 95000000,
  },
  {
    id: 6,
    facilityName: "Downtown Medical Plaza",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "987 Downtown Ave, Seattle, WA 98101",
    facilityId: "FAC006",
    ownerName: "Jennifer Wilson",
    ownerEmail: "j.wilson@example.com",
    ownerId: "OWN006",
    registerDate: "2023-04-22",
    status: "Pending",
    province: "p2",
    district: "d7",
    revenue: 92000000,
  },
  {
    id: 7,
    facilityName: "Riverside Health Center",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "159 Riverside Dr, Austin, TX 78701",
    facilityId: "FAC007",
    ownerName: "David Miller",
    ownerEmail: "david.m@example.com",
    ownerId: "OWN007",
    registerDate: "2022-12-30",
    status: "Active",
    province: "p3",
    district: "d11",
    revenue: 145000000,
  },
  {
    id: 8,
    facilityName: "Mountain View Hospital",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "753 Mountain Rd, Denver, CO 80202",
    facilityId: "FAC008",
    ownerName: "Lisa Taylor",
    ownerEmail: "lisa.t@example.com",
    ownerId: "OWN008",
    registerDate: "2023-05-15",
    status: "Active",
    province: "p3",
    district: "d12",
    revenue: 195000000,
  },
  {
    id: 9,
    facilityName: "Oceanside Medical Group",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "426 Ocean Dr, San Diego, CA 92101",
    facilityId: "FAC009",
    ownerName: "Thomas Anderson",
    ownerEmail: "t.anderson@example.com",
    ownerId: "OWN009",
    registerDate: "2023-01-28",
    status: "Inactive",
    province: "p2",
    district: "d8",
    revenue: 78000000,
  },
  {
    id: 10,
    facilityName: "Valley Care Center",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "871 Valley Blvd, Phoenix, AZ 85001",
    facilityId: "FAC010",
    ownerName: "Amanda Martinez",
    ownerEmail: "a.martinez@example.com",
    ownerId: "OWN010",
    registerDate: "2022-10-12",
    status: "Active",
    province: "p3",
    district: "d10",
    revenue: 155000000,
  },
  {
    id: 11,
    facilityName: "Lakeside Wellness Clinic",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "329 Lake St, Chicago, IL 60007",
    facilityId: "FAC011",
    ownerName: "Robert Williams",
    ownerEmail: "r.williams@example.com",
    ownerId: "OWN003",
    registerDate: "2023-06-05",
    status: "Pending",
    province: "p5",
    district: "d18",
    revenue: 90000000,
  },
  {
    id: 12,
    facilityName: "Parkview Medical Center",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "512 Park Ave, Atlanta, GA 30301",
    facilityId: "FAC012",
    ownerName: "John Smith",
    ownerEmail: "john.smith@example.com",
    ownerId: "OWN001",
    registerDate: "2022-08-22",
    status: "Active",
    province: "p4",
    district: "d15",
    revenue: 85000000,
  },
  {
    id: 13,
    facilityName: "Harbor View Clinic",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "789 Harbor Blvd, San Francisco, CA 94111",
    facilityId: "FAC013",
    ownerName: "John Smith",
    ownerEmail: "john.smith@example.com",
    ownerId: "OWN001",
    registerDate: "2023-03-18",
    status: "Active",
    province: "p2",
    district: "d7",
    revenue: 90000000,
  },
  {
    id: 14,
    facilityName: "Sunset Medical Center",
    facilityImage: "/placeholder.svg?height=40&width=40",
    facilityAddress: "456 Sunset Ave, Miami, FL 33139",
    facilityId: "FAC014",
    ownerName: "Michael Brown",
    ownerEmail: "m.brown@example.com",
    ownerId: "OWN005",
    registerDate: "2023-01-10",
    status: "Active",
    province: "p4",
    district: "d14",
    revenue: 80000000,
  },
]

// Helper function to get owner by ID
export function getOwnerById(ownerId: string): Owner | null {
  return owners.find((owner) => owner.ownerId === ownerId) || null
}

// Helper function to get facilities by owner ID
export function getFacilitiesByOwnerId(ownerId: string): Facility[] {
  return facilities.filter((facility) => facility.ownerId === ownerId)
}

// Format currency to VND format
export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

// Format date to be more readable
export function formatDate(dateString: string): string {
  const date = new Date(dateString)
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  })
}

import type { User, Post, Comment } from "./types"

export const users: User[] = [
  {
    id: "user-1",
    name: "Alex Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Admin",
    isOnline: true,
    verified: true,
  },
  {
    id: "user-2",
    name: "Albert Flores",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Moderator",
    isOnline: true,
    verified: true,
  },
  {
    id: "user-3",
    name: "Ralph Edwards",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: false,
  },
  {
    id: "user-4",
    name: "Sophia Davis",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: true,
  },
  {
    id: "user-5",
    name: "Emma Watson",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: true,
    verified: true,
  },
  {
    id: "user-6",
    name: "James Smith",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: true,
  },
]

const replies: Comment[] = [
  {
    id: "reply-1",
    author: users[3],
    content: "I completely agree with your point. This is really insightful!",
    createdAt: new Date(2023, 4, 19, 11, 45),
    likes: 2,
    isLiked: false,
  },
  {
    id: "reply-2",
    author: users[4],
    content: "Thanks for sharing this perspective. I hadn't thought about it that way before.",
    createdAt: new Date(2023, 4, 19, 12, 15),
    likes: 1,
    isLiked: false,
  },
]

const comments: Comment[] = [
  {
    id: "comment-1",
    author: users[2],
    content:
      "This is a fantastic article! The TF-IDF concept has been underutilized for too long. I've been implementing this in my SEO strategy with great results.",
    createdAt: new Date(2023, 4, 19, 10, 30),
    likes: 5,
    isLiked: false,
    replies: [replies[0]],
  },
  {
    id: "comment-2",
    author: users[2],
    content: "I'd love to see more content like this. Perhaps a follow-up article on practical implementation steps?",
    createdAt: new Date(2023, 4, 19, 11, 15),
    likes: 3,
    isLiked: false,
  },
  {
    id: "comment-3",
    author: users[2],
    content: "One question - how does this compare to other content optimization techniques like LSI keywords?",
    createdAt: new Date(2023, 4, 19, 12, 0),
    likes: 1,
    isLiked: false,
    replies: [replies[1]],
  },
  {
    id: "comment-4",
    author: users[3],
    content:
      "Very helpful information! I've been struggling with content optimization and this gives me a new approach to try.",
    createdAt: new Date(2023, 4, 19, 13, 30),
    likes: 2,
    isLiked: false,
  },
  {
    id: "comment-5",
    author: users[0],
    content: "I've applied this method and seen significant improvements in my search rankings. Highly recommended!",
    createdAt: new Date(2023, 4, 19, 14, 45),
    likes: 3,
    isLiked: false,
  },
]

export const initialPosts: Post[] = [
  {
    id: "post-1",
    author: users[1],
    title: "TF-IDF Content Optimisation: Your Guide to an Underappreciated SEO Concept",
    content:
      "Term Frequency-Inverse Document Frequency (TF-IDF) is a powerful yet often overlooked technique in SEO content optimization.\n\nUnlike basic keyword density, TF-IDF considers both how frequently a term appears in your content and how unique that term is across a collection of documents. This helps create content that's both relevant and distinctive.\n\nHave you implemented TF-IDF in your content strategy? I'd love to hear your experiences!",
    category: "SEO",
    mediaUrls: ["/placeholder.svg?height=400&width=600"],
    createdAt: new Date(2023, 4, 19, 9, 0),
    likes: 15,
    comments: [comments[0], comments[1], comments[2]],
    isLiked: false,
    shares: 5,
    bookmarked: false,
    privacy: "public",
  },
  {
    id: "post-2",
    author: users[2],
    title: "The Future of Web Development: Trends to Watch in 2023",
    content:
      "As we move further into 2023, several exciting trends are shaping the future of web development:\n\n1. AI-powered development tools\n2. WebAssembly going mainstream\n3. Serverless architectures becoming the norm\n4. Micro-frontends for scalable applications\n5. Improved accessibility standards\n\nWhich of these trends are you most excited about?",
    category: "WebDev",
    mediaUrls: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    createdAt: new Date(2023, 4, 18, 14, 30),
    likes: 27,
    comments: [comments[3], comments[4]],
    isLiked: true,
    shares: 12,
    bookmarked: true,
    privacy: "friends",
  },
  {
    id: "post-3",
    author: users[4],
    content:
      "Just finished an amazing UX design workshop! Learning about user research techniques and prototyping tools has been incredibly valuable. Can't wait to apply these principles to my next project.",
    category: "Design",
    mediaUrls: ["/placeholder.svg?height=400&width=600"],
    createdAt: new Date(2023, 4, 18, 10, 15),
    likes: 42,
    comments: [],
    isLiked: false,
    shares: 3,
    bookmarked: false,
    privacy: "public",
  },
]

export const conversationsData: ConversationType[] = [
  {
    id: 1,
    name: "Ammi Watts",
    avatar: "/placeholder.svg?height=40&width=40",
    lastMessage: "Hello there",
    time: "06:32 PM",
    unread: 0,
    online: true,
    isActive: true,
    starred: false,
    messages: [
      { id: 1, text: "Hello there", sent: false, time: "06:32 PM" },
      { id: 2, text: "Are you looking to book a badminton court with us?", sent: false, time: "06:33 PM" },
      { id: 3, text: "Yes, that's right", sent: true, time: "06:34 PM" },
      {
        id: 4,
        text: "I'd like to book this court",
        sent: true,
        time: "06:35 PM",
        imageUrl: "/placeholder.svg?height=200&width=300",
      },
    ],
  },
  {
    id: 2,
    name: "Jennifer Markus",
    avatar: "/placeholder.svg?height=40&width=40",
    lastMessage: "Hey! Did you finish the Hi-Fi wireframes for flora app design?",
    time: "05:30 PM",
    unread: 1,
    online: false,
    isActive: false,
    starred: true,
    messages: [
      { id: 1, text: "Hi there! How's the project coming along?", sent: false, time: "05:25 PM" },
      { id: 2, text: "Hey! Did you finish the Hi-Fi wireframes for flora app design?", sent: false, time: "05:30 PM" },
    ],
  },
  {
    id: 3,
    name: "Iva Ryan",
    avatar: "/placeholder.svg?height=40&width=40",
    lastMessage: "Hey! Did you finish the Hi-Fi wireframes for flora app design?",
    time: "05:30 PM",
    unread: 0,
    online: true,
    isActive: false,
    starred: false,
    messages: [
      { id: 1, text: "Hey! Did you finish the Hi-Fi wireframes for flora app design?", sent: false, time: "05:30 PM" },
    ],
  },
  {
    id: 4,
    name: "Mai Duy",
    avatar: "/placeholder.svg?height=40&width=40",
    lastMessage: "I'll send you the court schedule tomorrow",
    time: "04:15 PM",
    unread: 2,
    online: true,
    isActive: false,
    starred: true,
    messages: [
      { id: 1, text: "Hello, I'd like to ask about badminton court prices", sent: true, time: "04:10 PM" },
      {
        id: 2,
        text: "The court rental is $20/hour during peak hours and $15/hour during off-peak hours",
        sent: false,
        time: "04:12 PM",
      },
      { id: 3, text: "Thank you, I'd like to book a court for next Saturday", sent: true, time: "04:14 PM" },
      { id: 4, text: "I'll send you the court schedule tomorrow", sent: false, time: "04:15 PM" },
      {
        id: 5,
        text: "",
        sent: false,
        time: "04:20 PM",
        imageUrl: "/placeholder.svg?height=200&width=300",
      },
    ],
  },
  {
    id: 5,
    name: "John Smith",
    avatar: "/placeholder.svg?height=40&width=40",
    lastMessage: "Can you send me more information about the badminton training courses?",
    time: "Yesterday",
    unread: 0,
    online: false,
    isActive: false,
    starred: false,
    messages: [
      {
        id: 1,
        text: "Can you send me more information about the badminton training courses?",
        sent: false,
        time: "Yesterday",
      },
    ],
  },
]









