// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.Infrastructure.Persistence;

#nullable disable

namespace OrderService.Infrastructure.Persistence.Migrations;

[DbContext(typeof(DataContext))]
partial class DataContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

        modelBuilder.Entity("OrderService.Core.Domain.Entities.Order", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("CourtId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("FacilityName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ImageUrl")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("Price")
                    .HasColumnType("TEXT");

                b.Property<int>("State")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<Guid>("UserId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Orders");
            });

        modelBuilder.Entity("OrderService.Core.Domain.Entities.Order", b =>
            {
                b.OwnsOne("OrderService.Core.Domain.Entities.DateTimePeriod", "DateTimePeriod", b1 =>
                    {
                        b1.Property<Guid>("OrderId")
                            .HasColumnType("TEXT");

                        b1.Property<DateTime>("HourFrom")
                            .HasColumnType("TEXT");

                        b1.Property<DateTime>("HourTo")
                            .HasColumnType("TEXT");

                        b1.HasKey("OrderId");

                        b1.ToTable("Orders");

                        b1.WithOwner()
                            .HasForeignKey("OrderId");
                    });

                b.Navigation("DateTimePeriod")
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
