import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main>
        <SidebarTrigger />
        <html lang="en">
        <body
          className={`${inter.variable} antialiased h-screen overflow-hidden`}
        >
          <div className="h-full overflow-auto">
            <div className="min-h-screenoverflow-auto">{children}</div>
          </div>
        </body>
      </html>
        </main>
    </SidebarProvider>
  );
}
